# Generated by Django 4.0.2 on 2022-02-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_alter_answerexercise_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise', unique=True),
        ),
    ]
